<?php

return [
    'divisions' => [
        'Dhaka' => 'Dhaka',
        'Chittagong' => 'Chittagong',
        'Rajshahi' => 'Rajshahi',
        'Khulna' => 'Khulna',
        'Barisal' => 'Barisal',
        'Sylhet' => 'Sylhet',
        'Rangpur' => 'Rangpur',
        'Mymensingh' => 'Mymensingh',
    ],

    'shipping_costs' => [
        'Dhaka' => 100,
        'Chittagong' => 150,
        'Rajshahi' => 150,
        'Khulna' => 150,
        'Barisal' => 150,
        'Sylhet' => 150,
        'Rangpur' => 150,
        'Mymensingh' => 150,
    ],

    'districts' => [
        'Dhaka' => [
            'Dhaka' => 'Dhaka',
            'Faridpur' => 'Faridpur',
            'Gazipur' => 'Gazipur',
            'Gopalganj' => 'Gopalganj',
            'Kishoreganj' => 'Kishoreganj',
            'Madaripur' => 'Madaripur',
            'Manikganj' => 'Manikganj',
            'Munshiganj' => 'Munshiganj',
            'Narayanganj' => 'Narayanganj',
            'Narsingdi' => 'Narsingdi',
            'Rajbari' => 'Rajbari',
            'Shariatpur' => 'Shariatpur',
            'Tangail' => 'Tangail',
        ],
        'Chittagong' => [
            'Bandarban' => 'Bandarban',
            'Brahmanbaria' => 'Brahmanbaria',
            'Chandpur' => 'Chandpur',
            'Chittagong' => 'Chittagong',
            'Comilla' => 'Comilla',
            'Coxs_bazar' => "Cox's Bazar",
            'Feni' => 'Feni',
            'Khagrachhari' => 'Khagrachhari',
            'Lakshmipur' => 'Lakshmipur',
            'Noakhali' => 'Noakhali',
            'Rangamati' => 'Rangamati',
        ],
        'Rajshahi' => [
            'Bogra' => 'Bogra',
            'Joypurhat' => 'Joypurhat',
            'Naogaon' => 'Naogaon',
            'Natore' => 'Natore',
            'Nawabganj' => 'Nawabganj',
            'Pabna' => 'Pabna',
            'Rajshahi' => 'Rajshahi',
            'Sirajganj' => 'Sirajganj',
        ],
        'Khulna' => [
            'Bagerhat' => 'Bagerhat',
            'Chuadanga' => 'Chuadanga',
            'Jessore' => 'Jessore',
            'Jhenaidah' => 'Jhenaidah',
            'Khulna' => 'Khulna',
            'Kushtia' => 'Kushtia',
            'Magura' => 'Magura',
            'Meherpur' => 'Meherpur',
            'Narail' => 'Narail',
            'Satkhira' => 'Satkhira',
        ],
        'Barisal' => [
            'Barguna' => 'Barguna',
            'Barisal' => 'Barisal',
            'Bhola' => 'Bhola',
            'Jhalokati' => 'Jhalokati',
            'Patuakhali' => 'Patuakhali',
            'Pirojpur' => 'Pirojpur',
        ],
        'Sylhet' => [
            'Habiganj' => 'Habiganj',
            'Moulvibazar' => 'Moulvibazar',
            'Sunamganj' => 'Sunamganj',
            'Sylhet' => 'Sylhet',
        ],
        'Rangpur' => [
            'Dinajpur' => 'Dinajpur',
            'Gaibandha' => 'Gaibandha',
            'Kurigram' => 'Kurigram',
            'Lalmonirhat' => 'Lalmonirhat',
            'Nilphamari' => 'Nilphamari',
            'Panchagarh' => 'Panchagarh',
            'Rangpur' => 'Rangpur',
            'Thakurgaon' => 'Thakurgaon',
        ],
        'Mymensingh' => [
            'Jamalpur' => 'Jamalpur',
            'Mymensingh' => 'Mymensingh',
            'Netrakona' => 'Netrakona',
            'Sherpur' => 'Sherpur',
        ],
    ],
];
